import elecGinPhoto from './images/electricGin.png';
import ohmsWhiskeyPhoto from './images/ohmsWhiskey.png';
import kirchoffsBeerPhoto from './images/kirchoffsBeer.png';
import teslasCocktailPhoto from './images/teslasCocktail.png';
import threephaseSandwichPhoto from './images/threephaseSandwich.png';
import theHighVoltageBurgerPhoto from './images/theHighVoltageBurger.png';
import pnpCheesecakePhoto from './images/pnpCheesecake.png';

export default function menu()
{
	const element = document.createElement('div');
	element.setAttribute('id', 'page');
	const headingContainer = document.createElement('div');
	const heading = document.createElement('h1');
	heading.setAttribute('id', 'title');
	heading.innerHTML = "Menu";
	headingContainer.appendChild(heading);
	element.appendChild(headingContainer);
	const drinksContainer = document.createElement('div');
	drinksContainer.classList.add('type-container');
	const drinks = document.createElement('h2');
	drinks.innerHTML = 'Drinks';
	drinksContainer.appendChild(drinks);
	element.appendChild(drinksContainer);
	const electricGinContainer = document.createElement('div');
	electricGinContainer.classList.add('menu-items');
	const electricGin = document.createElement('h3');
	electricGin.classList.add('item-name');
	electricGin.innerHTML = 'Electric Gin';
	electricGinContainer.appendChild(electricGin);
	const electricGinDiv = document.createElement('div');
	electricGinDiv.classList.add('item-div');
	const electricGinDesc = document.createElement('p');
	electricGinDesc.innerHTML = 'Electrical spirit london dry gin mixed with tonic and blue curacao.';
	const myElecGin = new Image();
	myElecGin.src = elecGinPhoto;
	myElecGin.classList.add('menu-image');
	electricGinDiv.appendChild(electricGinDesc);
	electricGinDiv.appendChild(myElecGin);
	electricGinContainer.appendChild(electricGinDiv);
	const ginPrice = document.createElement('p');
	ginPrice.classList.add('price');
	ginPrice.innerHTML = 'Price: 500 EERs';
	electricGinContainer.appendChild(ginPrice);
	element.appendChild(electricGinContainer);
	const ohmsWhiskeyContainer = document.createElement('div');
	ohmsWhiskeyContainer.classList.add('menu-items');
	const ohmsWhiskey = document.createElement('h3');
	ohmsWhiskey.classList.add('item-name');
	ohmsWhiskey.innerHTML = "Ohm's Whiskey";
	ohmsWhiskeyContainer.appendChild(ohmsWhiskey);
	const ohmsWhiskeyDiv = document.createElement('div');
	ohmsWhiskeyDiv.classList.add('item-div');
	const ohmsWhiskeyDesc = document.createElement('p');
	ohmsWhiskeyDesc.innerHTML = 'Whiskey mixed with blood orange juice and a jalapeno to add a bit of spiciness.';
	const myWhiskey = new Image();
	myWhiskey.src = ohmsWhiskeyPhoto;
	myWhiskey.classList.add('menu-image');
	ohmsWhiskeyDiv.appendChild(ohmsWhiskeyDesc);
	ohmsWhiskeyDiv.appendChild(myWhiskey);
	ohmsWhiskeyContainer.appendChild(ohmsWhiskeyDiv);
	const whiskeyPrice = document.createElement('p');
	whiskeyPrice.classList.add('price');
	whiskeyPrice.innerHTML = 'Price: 700 EERs';
	ohmsWhiskeyContainer.appendChild(whiskeyPrice);
	element.appendChild(ohmsWhiskeyContainer);
	const kirchoffsBeerContainer = document.createElement('div');
	kirchoffsBeerContainer.classList.add('menu-items');
	const kirchoffsBeer = document.createElement('h3');
	kirchoffsBeer.classList.add('item-name');
	kirchoffsBeer.innerHTML = "Kirchoff's Beer";
	kirchoffsBeerContainer.appendChild(kirchoffsBeer);
	const kirchoffsBeerDiv = document.createElement('div');
	kirchoffsBeerDiv.classList.add('item-div');
	const kirchoffsBeerDesc = document.createElement('p');
	kirchoffsBeerDesc.innerHTML = 'The classic U-Boot cocktail but instead of vodka we use Korn.'; 
	const myBeer = new Image();
	myBeer.src = kirchoffsBeerPhoto;
	myBeer.classList.add('menu-image');
	kirchoffsBeerDiv.appendChild(kirchoffsBeerDesc);
	kirchoffsBeerDiv.appendChild(myBeer);
	kirchoffsBeerContainer.appendChild(kirchoffsBeerDiv);
	const beerPrice = document.createElement('p');
	beerPrice.classList.add('price');
	beerPrice.innerHTML = 'Price: 300 EERs';
	kirchoffsBeerContainer.appendChild(beerPrice);
	element.appendChild(kirchoffsBeerContainer);
	const teslasCocktailContainer = document.createElement('div');
	teslasCocktailContainer.classList.add('menu-items');
	const teslasCocktail = document.createElement('h3');
	teslasCocktail.classList.add('item-name');
	teslasCocktail.innerHTML = "Tesla's Cocktail";
	teslasCocktailContainer.appendChild(teslasCocktail);
	const teslasCocktailDiv = document.createElement('div');
	teslasCocktailDiv.classList.add('item-div');
	const teslasCocktailDesc = document.createElement('p');
	teslasCocktailDesc.innerHTML = 'Tom Collins but to make it more interesting instead of gin, we use plum brandy.';
	const myCocktail = new Image();
	myCocktail.src = teslasCocktailPhoto;
	myCocktail.classList.add('menu-image');
	teslasCocktailDiv.appendChild(teslasCocktailDesc);
	teslasCocktailDiv.appendChild(myCocktail);
	teslasCocktailContainer.appendChild(teslasCocktailDiv);
	const cocktailPrice = document.createElement('p');
	cocktailPrice.classList.add('price');
	cocktailPrice.innerHTML = 'Price: 600 EERs';
	teslasCocktailContainer.appendChild(cocktailPrice);
	element.appendChild(teslasCocktailContainer);
	const foodContainer = document.createElement('div');
	foodContainer.classList.add('type-container');
	const food = document.createElement('h2');
	food.innerHTML = 'Food';
	foodContainer.appendChild(food);
	element.appendChild(foodContainer);
	const threephaseSandwichContainer = document.createElement('div');
	threephaseSandwichContainer.classList.add('menu-items');
	const threephaseSandwich = document.createElement('h3');
	threephaseSandwich.classList.add('item-name');
	threephaseSandwich.innerHTML = 'Threephase Sandwich';
	threephaseSandwichContainer.appendChild(threephaseSandwich);
	const threephaseSandwichDiv = document.createElement('div');
	threephaseSandwichDiv.classList.add('item-div');
	const threephaseSandwichDesc = document.createElement('p');
	threephaseSandwichDesc.innerHTML = 'The forbidden sandwich';
	const mySandwich = new Image();
	mySandwich.src = threephaseSandwichPhoto;
	mySandwich.classList.add('menu-image');
	threephaseSandwichDiv.appendChild(threephaseSandwichDesc);
	threephaseSandwichDiv.appendChild(mySandwich);
	threephaseSandwichContainer.appendChild(threephaseSandwichDiv);
	const sandwichPrice = document.createElement('p');
	sandwichPrice.classList.add('price');
	sandwichPrice.innerHTML = 'Price: 400 EERs';
	threephaseSandwichContainer.appendChild(sandwichPrice);
	element.appendChild(threephaseSandwichContainer);
	const theHighVoltageBurgerContainer = document.createElement('div');
	theHighVoltageBurgerContainer.classList.add('menu-items');
	const theHighVoltageBurger = document.createElement('h3');
	theHighVoltageBurger.classList.add('item-name');
	theHighVoltageBurger.innerHTML = 'The High Voltage Burger';
	theHighVoltageBurgerContainer.appendChild(theHighVoltageBurger)
	const theHighVoltageBurgerDiv = document.createElement('div');
	theHighVoltageBurgerDiv.classList.add('item-div');
	const theHighVoltageBurgerDesc = document.createElement('p');
	theHighVoltageBurgerDesc.innerHTML = "The power of The High Voltage Burger can't be described by words, you have to try it for yourself.";
	const myBurger = new Image();
	myBurger.src = theHighVoltageBurgerPhoto;
	myBurger.classList.add('menu-image');
	theHighVoltageBurgerDiv.appendChild(theHighVoltageBurgerDesc);
	theHighVoltageBurgerDiv.appendChild(myBurger);
	theHighVoltageBurgerContainer.appendChild(theHighVoltageBurgerDiv)
	const burgerPrice = document.createElement('p');
	burgerPrice.classList.add('price');
	burgerPrice.innerHTML = 'Price: 600 EERs';
	theHighVoltageBurgerContainer.appendChild(burgerPrice);
	element.appendChild(theHighVoltageBurgerContainer);
	const dessertsContainer = document.createElement('div');
	dessertsContainer.classList.add('type-container');
	const desserts = document.createElement('h2');
	desserts.classList.add('item-name');
	desserts.innerHTML = 'Desserts';
	dessertsContainer.appendChild(desserts);
	element.appendChild(dessertsContainer);
	const pnpCheesecakeContainer = document.createElement('div');
	pnpCheesecakeContainer.classList.add('menu-items');
	const pnpCheesecake = document.createElement('h3');
	pnpCheesecake.classList.add('item-name');
	pnpCheesecake.innerHTML = "PNP Cheesecake";
	pnpCheesecakeContainer.appendChild(pnpCheesecake);
	const pnpCheesecakeDiv = document.createElement('div');
	pnpCheesecakeDiv.classList.add('item-div');
	const pnpCheesecakeDesc = document.createElement('p');
	pnpCheesecakeDesc.innerHTML = "The PNP Cheesecake consists of three layers. Graham crackers as it's base, the classic second layer mascarpone cheese, and another layer of graham crackers on top mixed with blueberry jelly.";
	const myCheesecake = new Image();
	myCheesecake.src = pnpCheesecakePhoto;
	myCheesecake.classList.add('menu-image');
	pnpCheesecakeDiv.appendChild(pnpCheesecakeDesc);
	pnpCheesecakeDiv.appendChild(myCheesecake);
	pnpCheesecakeContainer.appendChild(pnpCheesecakeDiv);
	const cheesecakePrice = document.createElement('p');
	cheesecakePrice.classList.add('price');
	cheesecakePrice.innerHTML = 'Price: 400 EERs';
	pnpCheesecakeContainer.appendChild(cheesecakePrice);
	element.appendChild(pnpCheesecakeContainer);
	return element;
}
